trigger: none 

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: citadel-shared-vars

steps:
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.4'

- script: 'gem install bundler'
  displayName: 'gem install bundler'

- script: 'bundle install'
  displayName: 'bundle install'

- script: 'ALGOLIA_API_KEY=$(algolia-admin-key) bundle exec jekyll algolia'
  displayName: 'run algolia reindex'