name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: none

resources:
  containers:
  - container: jekyll_container
    image: bencuk/temp
    #options: --volume=/home/vsts/work/1/s:/srv/jekyll

jobs:
- job: jekyllbuild
  displayName: Build site in jekyll container
  pool: Hosted Ubuntu 1604
  container: jekyll_container
  steps:
  - script: ls

- job: copy
  dependsOn: jekyllbuild
  displayName: Copy site
  pool: Hosted Ubuntu 1604
  steps:
  - script: ls
