# No triggers, run on schedule instead
trigger: none 
pr: none

queue:
  name: Hosted Ubuntu 1604

# Must pre-created & populated
variables:
  - group: citadel-shared-vars

steps:
- task: UseRubyVersion@0
  displayName: 'Use latest Ruby version'

- script: 'ruby -v'
  displayName: 'Ruby version'

- script: 'gem install bundler -v 1.17.3'
  displayName: 'Install bundler rubbish'

- script: 'bundle install'
  displayName: 'Run bundle install'

- script: 'ALGOLIA_API_KEY=$(algolia-admin-key) bundle exec jekyll algolia'
  displayName: 'Run algolia reindex'

# Note. We have to echo the API key to a special file for the stupid thing to work
# - script: |
#     mkdir -p _site
#     touch Gemfile.lock
#     chmod a+rw _site Gemfile.lock
#     echo $(algolia-admin-key) > _algolia_api_key
#     docker run --rm --volume="$PWD:/srv/jekyll" jekyll/builder jekyll algolia
#   displayName: Docker run jekyll algolia reindex
