#
# Updated pipeline for Azure Search
# Builds the site then uploads all .json to blob storage for indexing
#

# No triggers, run on schedule instead
trigger: none 
pr: none

queue:
  name: Hosted Ubuntu 1604

# Must pre-created & populated
variables:
  - group: citadel-shared-vars

steps:
- script: 'curl -v -H "api-key: $(search-admin-key)" -d "" -X POST "https://$(search-account).search.windows.net/indexers/$(search-indexer)/run?api-version=2017-11-11"'
  displayName: 'Call Azure Search API to run reindex'

# - task: UseRubyVersion@0
#   displayName: 'Use latest Ruby version'

# - script: 'gem install bundler -v 1.17.3'
#   displayName: 'Install bundler at version 1.17.3'

# - script: 'bundle install'
#   displayName: 'Run bundle install'

# - script: 'bundle exec jekyll build'
#   displayName: 'Run jekyll and build site'

# - script: 'az storage blob upload-batch -s _site -d site-json  --pattern "*.json" --account-name=$(storage-acct-name) --account-key="$(storage-acct-key)" --no-progress'
#   displayName: 'Upload JSON output to blobs for indexing'

# - script: 'curl -H "api-key: $(search-admin-key)" -d "" -X POST "https://$(search-account).search.windows.net/indexers/$(search-indexer)/run?api-version=2017-11-11"'
#   displayName: 'Call Azure Search to run reindex'


# Note. We have to echo the API key to a special file for the stupid thing to work
# - script: |
#     mkdir -p _site
#     touch Gemfile.lock
#     chmod a+rw _site Gemfile.lock
#     echo $(algolia-admin-key) > _algolia_api_key
#     docker run --rm --volume="$PWD:/srv/jekyll" jekyll/builder jekyll algolia
#   displayName: Docker run jekyll algolia reindex