# No triggers, run on schedule instead
trigger: none 
pr: none

queue:
  name: Hosted Ubuntu 1604

# Must pre-created & populated
variables:
  - group: citadel-shared-vars

steps:
# - task: UseRubyVersion@0
#   displayName: 'Use Ruby >= 2.4'

# - script: 'gem install bundler'
#   displayName: 'gem install bundler'

# - script: 'bundle install'
#   displayName: 'bundle install'

# - script: 'ALGOLIA_API_KEY=$(algolia-admin-key) bundle exec jekyll algolia'
#   displayName: 'run algolia reindex'

- script: 'printenv'
  displayName: 'printenv'

# Note. We do not need to explictly reference or pass ALGOLIA_API_KEY 
#       it should be defined and set in citadel-shared-vars
- script: |
    mkdir -p $PWD/_site
    touch Gemfile.lock
    chmod a+rw $PWD/_site Gemfile.lock
    docker run --rm --volume="$PWD:/srv/jekyll" jekyll/builder jekyll algolia
  displayName: Docker run jekyll algolia reindex
  env: 
    ALGOLIA_API_KEY: $(algolia-admin-key)
