---
# Playbook to add additional users
- hosts: localhost
  become: yes
  tasks:
    - name: Add users to the ansible group
      user:
        name: "{{ item.id }}"
        comment: "{{ item.name }}"
        group: ansible
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        state: present
  loop:
    - { id: 'rita', name: 'Rita Hayworth' }
    - { id: 'sue',  name: 'Sue Perkins' }
    - { id: 'bob',  name: 'Bob Odenkirk' }
...