name: Build Search Index

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install dependencies
      run: |
        #gem install bundler -N
        gem install bundler -v '= 2.0.2' -N
        gem update bundler

    - run: bundle install

    - name: Build Site
      run: bundle exec jekyll build

    - name: Push site.json to Azure Search
      run: |
        curl -v -H "api-key: ${SEARCH_ADMIN_KEY}" -H "Content-Type: application/json" --data-binary "@_site/site.json" -X POST "https://${SEARCH_ACCOUNT}.search.windows.net/indexes/${SEARCH_INDEX}/docs/index?api-version=2017-11-11"
      env:
        SEARCH_ACCOUNT: ${{ secrets.SEARCH_ACCOUNT }}
        SEARCH_ADMIN_KEY: ${{ secrets.SEARCH_ADMIN_KEY }}
        SEARCH_INDEX: ${{ secrets.SEARCH_INDEX }}
